baseURL = 'https://debdyut.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'basic'

[params]
 author = "Debdyut Hajra"
 description = "My portfolio site"

 gh_url = "https://api.github.com/users"
 gh_user = "Debdyut"
